version: "3.8"
services:
  # Nginx server
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/logs/:/var/log/nginx/
    command: /tmp/run_nginx.sh
    environment:
      - DOLLAR=$
    env_file:
      - ./.env
    depends_on:
      - pyserver
    restart: always

  # FastAPI server
  pyserver:
    container_name: ${COMPOSE_PROJECT_NAME}_pyserver
    build:
      context: ../
      dockerfile: docker/Dockerfile-py
    expose:
      - ${PYSERVER_PORT}
    volumes:
      - ../src:/src
      - ../log:/log
    depends_on:
      - mysql
    command: bash -c "cd src && python main.py migrate && uvicorn main:app --host 0.0.0.0 --port ${PYSERVER_PORT} --reload"
    restart: always

  # PHP My Admin and MySQL server
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin
    expose:
      - ${PMA_APACHE_PORT}
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}

      # Auto login to MySQL
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}

      - APACHE_PORT=${PMA_APACHE_PORT}
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    platform: ${MYSQL_PLATFORM}
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always

networks:
  default:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network
